CXX=g++
SRC = SPKTool/spktool.cpp SPKConvert/spkconvert.cpp

OBJ = $(SRC:.cpp=.o)
BIN = $(SRC:.cpp=)

LIB = SPK/libspk.a SPK/libz.a SPK/lib7.a

# dependency makefiles, generated by gcc in target $(OBJ)
DEP = $(SRC:.cpp=.d)

CXXFLAGS = -MMD -MP

all: SPK/libspk.a SPKTool/spktool SPKConvert/spkconvert

### - Binary Compile

SPKTool/spktool: %: %.cpp $(LIB)
	$(CXX) $(CXXFLAGS) $^ -o $@

SPKConvert/spkconvert: %: %.cpp $(LIB)
	$(CXX) $(CXXFLAGS) $^ -o $@

### - Compile the libraries

SPK/libspk.a:
	make -C SPK -f Makefile	

# these are already compiled by the previous target
SPK/libz.a SPK/lib7.a:

### - Special targets
# use proper target even if a file named 'clean' is present
.PHONY: clean

clean:
	rm -f $(OBJ) $(DEP) $(BIN)
	make -C SPK -f Makefile	clean

install:
	cp $(BIN) ./

# update dependencies if necessary, before doing anything else
-include $(DEP)
